name: dms

services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
  dms-api:
    build:
      context: ./
      dockerfile: dms-api/Dockerfile
    container_name: dms-api
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    restart: unless-stopped
    command: sh -c "npx prisma migrate reset --force && node dist/dms-api/src/main"

  dms-frontend:
    build:
      context: ./
      dockerfile: dms-frontend/Dockerfile
    container_name: dms-frontend
    ports:
      - '5173:5173'
    depends_on:
      - dms-api
    restart: unless-stopped
